### ISSUE TITLE
Platform dependent iwslt.pt

### ISSUE THREAD

**Issue by comja** [harvardnlp/annotated-transformer#5]
Hello again!

When I tried to load the pre-trained model

`model = torch.load("iwslt.pt")`

it fails with the error message 

`RuntimeError: cuda runtime error (35) : CUDA driver version is insufficient for CUDA runtime version at torch/csrc/cuda/Module.cpp:107`

Is it possible (in addition to the entire model) to save just model weights so that I can load the model on any platform (it can be done with something like `torch.save(the_model.state_dict(), PATH)`)?

**Comment by ajay-sreeram** [comment]
* Try `torch.load('iwslt.pt', map_location=lambda storage, loc: storage)` this remaps everything onto CPU
* In MyIterator class try using `device=-1` instead of `device=0` and comment `model.cuda() and criterion.cuda()` now this works with cpu.

making these two changes worked for me on a machine without gpu

**Comment by srush** [comment]
I think this is the correct answer.
